import 'dart:ui';

class AppColor {
  AppColor._();

  static const Color white = Color(0xFFFFFFFF);
  static const Color scaffoldBg = Color(0xFFF5F5F7);
  static const Color primaryText = Color(0xFF1A1A2E);
  static const Color secondaryText = Color(0xFF6B7280);
  static const Color accentBlue = Color(0xFF3B82F6);
  static const Color cardDark = Color(0xFF1E1E2E);
  static const Color cardLightBlue = Color(0xFFE0F0FF);
  static const Color cardLightGreen = Color(0xFFE0F5E4);
  static const Color bottomNavActive = Color(0xFF3B82F6);
  static const Color bottomNavInactive = Color(0xFF9CA3AF);
  static const Color redBadge = Color(0xFFEF4444);
  static const Color divider = Color(0xFFE5E7EB);
  static const Color spendingPurple = Color(0xFFEDE9FE);
  static const Color spendingPurpleIcon = Color(0xFF7C3AED);
  static const Color spendingBlue = Color(0xFFDBEAFE);
  static const Color spendingBlueIcon = Color(0xFF3B82F6);
  static const Color spendingGreen = Color(0xFFD1FAE5);
  static const Color spendingGreenIcon = Color(0xFF10B981);
  static const Color creditCardGradientStart = Color(0xFFFFFFFF);
  static const Color creditCardGradientEnd = Color(0xFFDFF0FE);
  static const Color debitCardGradientStart = Color(0xFFFFFFFF);
  static const Color debitCardGradientEnd = Color(0xFFE2F6E7);
  static const Color savingsGradientStart = Color(0xFFE0F2FE);
  static const Color savingsGradientEnd = Color(0xFFBAE6FD);
  static const Color greyBg = Color(0xFFF3F4F6);
  static const Color black = Color(0xFF000000);
  static const Color transparent = Color(0x00000000);
  static const Color cardStarYellow = Color(0xFFFBBF24);
  static const Color masterCardRed = Color(0xFFEB001B);
  static const Color masterCardOrange = Color(0xFFF79E1B);
  static const Color surfaceSoft = Color(0xFFF5F5F7);
  static const Color surfaceMuted = Color(0xFFF1F2F4);
  static const Color surfaceLavender = Color(0xFFE8ECFA);
  static const Color surfaceMint = Color(0xFFDEF2EE);
  static const Color textStrong = Color(0xFF16181D);
  static const Color textMuted = Color(0xFF7B7C80);
  static const Color textMid = Color(0xFF2A2D33);
  static const Color paymentsBlue = Color(0xFF4F97EA);
  static const Color paymentsBlueSoft = Color(0xFFBFDFFF);
  static const Color paymentsBlueCard = Color(0xFF7EBBFA);
  static const Color paymentsMint = Color(0xFF56C5AA);
  static const Color badgeRed = Color(0xFFFF4D57);
  static const Color iconDark = Color(0xFF23262B);
  static const Color iconGrey = Color(0xFFABACB0);
  static const Color splashStart = Color(0xFFEAF5FF);
  static const Color splashEnd = Color(0xFFB8DEFF);
  static const Color splashCard = Color(0xFF5EA9F7);
  static const Color splashCardSoft = Color(0xFFD9ECFF);
  static const Color splashInk = Color(0xFF20324A);
}
